name = "DEIM"
uuid = "a3bcb729-cafc-47df-b351-c61ec7953f53"
authors = ["Flemming Holtorf"]
version = "0.1.0"

[deps]
Symbolics = "0c5d862f-8b57-4792-8d23-62f2024744c7"

[compat]
Symbolics = "4"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
